import assert from "node:assert/strict";
import { test } from "node:test";
import { spawnSync } from "node:child_process";
import { chownSync, chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseAllDocuments } from "yaml";
import { PROBE_BUDGET, probeBudget, type ProbeObservation } from "../../ops/inspection/cpa-work-probe-budget.ts";

test("mount/startup and exec clocks remain separate under the unchanged total cap", () => {
  const identity = { jobUid: "job-uid", podUid: "pod-uid", pvcUid: "pvc-uid" };
  const start = Date.parse("2026-10-09T09:00:00Z");
  const at = (seconds: number) => new Date(start + seconds * 1000).toISOString();
  const pending: ProbeObservation = { ...identity, ownerUid: identity.jobUid, claimName: "mtc-cpa-recovery-work-20261005", jobStartedAt: at(0), initFailed: false, state: { waiting: { reason: "ContainerCreating" } }, writeStarted: false, complete: false };
  const late = probeBudget(pending, identity, start + 61_000);
  assert.equal(late.status, "STARTUP_DEADLINE");
  assert.equal(late.bytes, null);
  assert.equal(late.execElapsedMs, null);
  assert.equal(late.execDeadline, null);
  assert.equal(late.stopRequired, true);
  assert.deepEqual(late.cleanupIdentity, identity);
  assert.equal(probeBudget({ ...pending, initFailed: true }, identity, start + 10_000).status, "STARTUP_FAILED");
  const running = { ...pending, state: { running: { startedAt: at(50) } } };
  const begun = probeBudget(running, identity, start + 51_000);
  assert.equal(begun.status, "EXECUTING");
  assert.equal(begun.execElapsedMs, 1000);
  assert.equal(begun.execDeadline, start + 50_000 + PROBE_BUDGET.execMs);
  assert.equal(probeBudget(running, identity, start + 175_000).status, "TOTAL_DEADLINE");
  assert.equal(probeBudget({ ...running, state: { running: { startedAt: at(0) } } }, identity, start + 165_000).status, "EXEC_DEADLINE");
  const done = { ...running, writeStarted: true, complete: true, state: { terminated: { startedAt: at(50), finishedAt: at(90), exitCode: 0 } } };
  assert.equal(probeBudget(done, identity, start + 100_000).status, "COMPLETE");
  assert.equal(probeBudget(done, identity, start + 100_000).bytes, 1024 ** 3);
  assert.equal(probeBudget({ ...done, complete: false, state: { terminated: { startedAt: at(50), finishedAt: at(90), exitCode: 1 } } }, identity, start + 100_000).status, "EXEC_FAILED");
  assert.throws(() => probeBudget({ ...done, writeStarted: false }, identity, start + 100_000), /MISSING_WRITE_START/);
  assert.throws(() => probeBudget(pending, { ...identity, podUid: "replacement" }, start + 1000), /IDENTITY_MISMATCH/);
  assert.throws(() => probeBudget({ ...pending, ownerUid: "other-job" }, identity, start + 1000), /TARGET_MISMATCH/);
  assert.throws(() => probeBudget({ ...pending, claimName: "frozen-original" }, identity, start + 1000), /TARGET_MISMATCH/);
});

test("review-only target probe uses pinned dd direct I/O under 128Mi/250m, never another file", { timeout: 210000 }, () => {
  assert.equal(process.env.GITHUB_ACTIONS, "true");
  assert.equal(process.getuid!(), 0);
  const [policy, job] = parseAllDocuments(readFileSync("ops/inspection/cpa-work-directio-20261006a.yaml", "utf8")).map((document) => document.toJSON());
  assert.deepEqual(policy.spec.ingress, []);
  assert.deepEqual(policy.spec.egress, []);
  assert.equal(job.spec.suspend, true);
  assert.equal(job.spec.backoffLimit, 0);
  assert.equal(job.spec.activeDeadlineSeconds + job.spec.template.spec.terminationGracePeriodSeconds, 180);
  assert.equal(Number(job.metadata.annotations["memeloop.io/startup-budget-seconds"]) * 1000, PROBE_BUDGET.startupMs);
  assert.equal(Number(job.metadata.annotations["memeloop.io/exec-budget-seconds"]) * 1000, PROBE_BUDGET.execMs);
  assert.equal(job.spec.activeDeadlineSeconds * 1000, PROBE_BUDGET.totalMs);
  const pod = job.spec.template.spec;
  assert.equal(pod.nodeSelector["kubernetes.io/hostname"], "sansheng-hv");
  assert.equal(pod.automountServiceAccountToken, false);
  assert.deepEqual(pod.volumes, [{ name: "destination", persistentVolumeClaim: { claimName: "mtc-cpa-recovery-work-20261005" } }]);
  const runtime = pod.containers[0];
  assert.deepEqual(runtime.resources.limits, { cpu: "250m", memory: "128Mi", "ephemeral-storage": "32Mi" });
  assert.ok(runtime.args[0].includes("oflag=direct conv=notrunc,fsync"));
  assert.ok(runtime.args[0].includes("iflag=direct"));
  const root = mkdtempSync(join(tmpdir(), "cpa-directio-gha-"));
  chmodSync(root, 0o755);
  const directory = join(root, "perf-directio-20261006a");
  const name = `cpa-directio-${process.pid}-${Date.now()}`;
  const retained = join(root, "old.partial");
  mkdirSync(directory, { mode: 0o700 });
  chownSync(directory, 10001, 10001);
  writeFileSync(retained, "preserve old partial", { flag: "wx" });
  let passed = false;
  try {
    const result = spawnSync("docker", ["run", "--name", name, "--network", "none", "--read-only", "--memory", "128m", "--memory-swap", "128m", "--cpus", "0.25", "--pids-limit", "32", "--cap-drop", "ALL", "--security-opt", "no-new-privileges", "--user", "10001:10001", "--volume", `${root}:/destination:rw`, "--entrypoint", runtime.command[0], runtime.image, ...runtime.command.slice(1), ...runtime.args], { encoding: "utf8", timeout: 180000 });
    const inspection = spawnSync("docker", ["inspect", name], { encoding: "utf8" });
    assert.equal(inspection.status, 0, inspection.stderr);
    const state = JSON.parse(inspection.stdout)[0];
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(state.State.OOMKilled, false);
    assert.equal(state.HostConfig.Memory, 128 * 1024 ** 2);
    assert.equal(state.HostConfig.MemorySwap, 128 * 1024 ** 2);
    assert.equal(state.HostConfig.NanoCpus, 250000000);
    assert.ok(result.stdout.includes("DIRECTIO_COMPLETE"));
    assert.equal(existsSync(join(directory, "probe.bin")), false);
    assert.equal(readFileSync(retained, "utf8"), "preserve old partial");
    passed = true;
    console.log(JSON.stringify({ passed, image: runtime.image, testedCommit: process.env.GITHUB_SHA, bytes: 1024 ** 3, stdout: result.stdout, stderr: result.stderr }));
  } finally {
    spawnSync("docker", ["rm", "--force", name], { stdio: "ignore" });
    if (process.env.RUNNER_TEMP) writeFileSync(join(process.env.RUNNER_TEMP, "cpa-work-directio-command-result.json"), JSON.stringify({ passed, image: runtime.image, testedCommit: process.env.GITHUB_SHA, bytes: 1024 ** 3 }) + "\n");
    rmSync(root, { recursive: true });
  }
});
